name: SegNAFNet-GoPro
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 42
grouped_masks: True

datasets:
  train:
    name: gopro-train
    type: PairedImageGroupMaskDataset
    dataroot_gt: ./datasets/GoPro/train/sharp_crops
    dataroot_lq: ./datasets/GoPro/train/blur_crops
    dataroot_mask: ./datasets/GoPro/train/grouped_masks_crops
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageGroupMaskDataset
    dataroot_gt: ./datasets/GoPro/test/target
    dataroot_lq: ./datasets/GoPro/test/input
    dataroot_mask: ./datasets/GoPro/test/grouped_masks
    io_backend:
      type: disk

network_g:
  type: SegNAFNetLocal
  width: 32
  seg_channel: 2
  mask_dropout: 0.5
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
